version: 0.2

env:
  variables:
    S3_BUCKET_NAME: "urlshort-cloudfront-website"
    CLOUDFRONT_DISTRIBUTION_ID: "E135O407T9WZ07"

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Entered the install phase..."
      - npm install -g pnpm
    finally:
      - echo "Install phase completed."
  pre_build:
    commands:
      - echo "Entered the pre_build phase..."
      - pnpm install
    finally:
      - echo "Pre_build phase completed."
  build:
    commands:
      - echo "Entered the build phase..."
      - pnpm run build
      - echo "Build completed on $(date)"
    finally:
      - echo "Build phase completed."
  post_build:
    commands:
      - echo "Entered the post_build phase..."
      - echo "Syncing dist/ to S3 bucket - $S3_BUCKET_NAME"
      - aws s3 sync dist/ s3://$S3_BUCKET_NAME/ --delete
      - echo "Invalidating CloudFront cache for distribution - $CLOUDFRONT_DISTRIBUTION_ID"
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
    finally:
      - echo "Post_build phase completed."

artifacts:
  files:
    - '**/*'
  base-directory: dist
  name: url-shortener-app-$(date +%Y-%m-%d-%H-%M-%S)

cache:
  paths:
    - node_modules/**/*
    - ~/.npm/**/*
    - ~/.pnpm-store/**/*
